### ISSUE TITLE
WOOL Editor - Bug: Editor sometimes removes escapes from translation strings

### ISSUE THREAD

**Issue by dennishofs** [woolplatform/wool#101]
**Editor Version:**
v1.10.3

**Desktop or Web version:** 
Desktop

**Operating System (Desktop) or Browser (Web):**
Windows

**Describe the Issue:**
We had a WOOL node containing custom markdown like `[[BUTTON_TO_ADMIN]]`. Because `[[` and `]]` are reserved in WOOL, we escaped it: `\[[BUTTON_TO_ADMIN\]]`. In the extracted translation strings the escapes were removed. I think they should be maintained so the translation strings are still WOOL code. After all we can also have `$username` in a translation string.

**Comment by borisvanschooten** [comment]
Should be fixed in 1.10.6. Please check if the workaround can be removed.
