### ISSUE TITLE
Add support for Pointers to other dialogues in Editor/Run 

### ISSUE THREAD

**Issue by hopdenakker** [woolplatform/wool#14]
When running a dialogue script from within the editor, selecting a reply option that leads to a different dialogue node (e.g. `[[Yes, let's go!|new-dialogue.Start]]`) currently does nothing. It would be nice to see something like "Dialogue ended. Next dialogue 'new-dialogue.wool' selected, starting at node 'Start').

**Comment by borisvanschooten** [comment]
Support added for electron version (BETA).
