### ISSUE TITLE
Editor "Run Mode" input type numeric issue

### ISSUE THREAD

**Issue by hopdenakker** [woolplatform/wool#31]
For example:

`[[Some relatively long pointer text for the field: <<input type="numeric" value="$variableName" min="0" max="1440">>|NextNode]]`

The "Run Mode" in the WOOL Editor doesn't actually check the input provided in the input field. It can be a String (where it should only allow numeric input), and numeric inputs can be provided outside of the given "min" and "max" bounds.

In addition, visually the rather long "before text" somewhat breaks the styling of the reply option.

**Comment by borisvanschooten** [comment]
These are two separate issues. The second iussue with the "before text" (and "after text") is now fixed. Layout looks better and the button is no longer split.

**Comment by borisvanschooten** [comment]
Simplewoolclient now checks type="numeric". Non-numeric input characters are rejected, and errors are given for invalid numbers and number outside min/max range.
