### ISSUE TITLE
WOOL Editor: Make "Start" and "End" node visually different in the Editor

### ISSUE THREAD

**Issue by hopdenakker** [woolplatform/wool#47]
-- Editor Version: 1.4.3
-- Web or Desktop: any
-- Operating System: any
-- Browser (for Web): any

---- Describe the Issue: ----
The "Start" and "End" nodes have a special meaning in WOOL. The Editor should make this more clear. For both nodes, they can have a different visual appearance. For the "End" node specifically, editing its contents should be disallowed.

**Comment by borisvanschooten** [comment]
Start and end nodes are now visually distinct from the other nodes. Having content in End node now results in an error.
