### ISSUE TITLE
WOOL Editor: "Changes not saved, proceed?" when opening a new dialogue immediately after saving the current one

### ISSUE THREAD

**Issue by mcabrita** [woolplatform/wool#51]
-- Editor Version: 1.4.3
-- Web or Desktop: Desktop
-- Operating System: Windows 10
-- Browser (for Web):

---- Describe the Issue: ----
When opening a new dialogue, I always receive the pop-up "Changes not saved, proceed?", even immediately after saving the file. The first times this happened I always opened the dialogues in the webbrowser to check if the changes were actually saved.

**Comment by borisvanschooten** [comment]
This problem should now be fixed.
