### ISSUE TITLE
WOOL Editor: "Save as..." option in wool desktop

### ISSUE THREAD

**Issue by mcabrita** [woolplatform/wool#52]
-- Editor Version: 1.4.3
-- Web or Desktop: Desktop
-- Operating System: Windows 10
-- Browser (for Web): -

---- Describe the Issue: ----
Include a "Save as..." option in the wool desktop application to be able to save dialogues with another name.

**Comment by borisvanschooten** [comment]
Complete file management functions are now available through the file tree. This replaces a "Save as" menu option. 
To "save as", right click on a file and select "copy file". Then rename the new file and/or drag it where you want it.
