### ISSUE TITLE
WOOL Editor: Only first part of the dialogue name is highlighted when linking dialogues

### ISSUE THREAD

**Issue by mcabrita** [woolplatform/wool#53]
-- Editor Version: 1.4.3
-- Web or Desktop: Desktop
-- Operating System: Windows 10
-- Browser (for Web):

---- Describe the Issue: ----
When the name of the new dialogue being linked to has a dash, only the part before the dash is highlighted (see example attached).

![bug-wool](https://user-images.githubusercontent.com/11629452/80802805-b5462700-8bb0-11ea-845d-9d131132edf2.PNG)

**Comment by borisvanschooten** [comment]
Syntax colouring was pretty much broken. I fixed and simplified it, also made the colours a bit darker.
