### ISSUE TITLE
WOOL Editor: Add option to fill in coach name automatically

### ISSUE THREAD

**Issue by mcabrita** [woolplatform/wool#54]
-- Editor Version: 1.4.3
-- Web or Desktop: Desktop
-- Operating System: Windows 10
-- Browser (for Web):

---- Describe the Issue: ----
Most of the times the dialogue only includes one coach. In these cases, to avoid errors caused by typos, it would be great if by default the name of the coach could be added automatically to each new node.

**Comment by hopdenakker** [comment]
This is a problem indeed. The Editor cannot "help" in any way with avoiding errors related to speaker names. I'm working on some design updates for the Editor to address this.

**Comment by borisvanschooten** [comment]
There is now an autocomplete function. You get a list of all currently used speaker names as soon as you click on the speaker field.   For the future, a more complete speaker management UI is planned.
