### ISSUE TITLE
WOOL Editor - Bug: Continue button behind agent image area

### ISSUE THREAD

**Issue by dennishofs** [woolplatform/wool#55]
**Editor Version:**
v1.4.2

**Desktop or Web version:** 
Desktop and Web

**Operating System (Desktop) or Browser (Web):**
Chrome, Firefox, Windows

**Describe the Issue:**
Depending on the window size, the Continue button sometimes gets behind the agent image area, so it doesn't capture clicks.

**Comment by borisvanschooten** [comment]
Fixed; the agent will no longer get in the way of clicking.
