### ISSUE TITLE
WOOL Misc: Move Electron package files in wooleditor folder

### ISSUE THREAD

**Issue by hopdenakker** [woolplatform/wool#57]
**Please describe your issue below:**
The package-lock.json and package.json files are part of the wooleditor, so it would be better if they are moved inside the wooleditor folder (also, I guess we can rename that folder to "editor").

**Comment by borisvanschooten** [comment]
package.json covers both html5/ and wooleditor/, that's why it's at the top level. html5 also contains things that can be used separately from the editor. I think it's best to move wooleditor into the html5 directory.

**Comment by hopdenakker** [comment]
Yes, makes sense!

**Comment by borisvanschooten** [comment]
wooleditor and package.json are now in html5/ I also did some other file moves I had wanted to do for awhile.
