### ISSUE TITLE
WOOL Editor - Bug: 

### ISSUE THREAD

**Issue by tbeinema** [woolplatform/wool#59]
**Editor Version:**
v1.4.3

**Desktop or Web version:** 
Desktop

**Operating System (Desktop) or Browser (Web):**
Windows

**Describe the Issue:**
If the node editing overlay is shown for a node in `Dialogue A' and `Dialogue B' is opened from the file management pane, the dialogue is loaded in the editor, but the old 'Dialogue A' node that was open for editing stays open on top of the newly loaded dialogue.

**Comment by borisvanschooten** [comment]
Fixed!
