### ISSUE TITLE
WOOL Editor - Bug: Missing ]] at last reply in node not marked/detected as error

### ISSUE THREAD

**Issue by tbeinema** [woolplatform/wool#67]
**Editor Version:**
v1.4.3

**Desktop or Web version:** 
Desktop

**Operating System (Desktop) or Browser (Web):**
Windows

**Describe the Issue:**
If the closing ']]' for the last reply in a node is missing this is not marked as an error in the dialogue. 

E.g.:
![afbeelding](https://user-images.githubusercontent.com/10047603/83875446-5dfb1f80-a737-11ea-9526-f782ea17361c.png)

**Comment by borisvanschooten** [comment]
An unclosed '[[' is actually not incorrect, as far as I know, it means literal text. The syntax colouring does shows it as an option, though. The editor now produces a warning for unclosed '[['.
