### ISSUE TITLE
WOOL Editor - Feature: Info on number of nodes (or 'about this dialogue'?)

### ISSUE THREAD

**Issue by tbeinema** [woolplatform/wool#70]
**Please describe what you would like to see added or changed to the WOOL Editor:**

While editing quite a large dialogue, I thought 'How many nodes would this dialogue have?'.
Thus, maybe it would be nice to be able to look up what the number of nodes in a dialogue is for the current dialogue?

This could for example be done by adding an 'about this dialogue'-type button in the menu, which can then show an overlay or pop-up with some dialogue information/stats?

**Comment by borisvanschooten** [comment]
The number of nodes is now visible next to the file name.
