### ISSUE TITLE
WOOL Language: Long-text type for long string inputs

### ISSUE THREAD

**Issue by lenabrandl** [woolplatform/wool#71]
**Please describe what you would like to see changed or added to the WOOL language:**
A dedicated variable type ```long-text``` for longer text inputs, such as diary entries, story telling, or reflection reports. Without a dedicated text type, project clients will be required to check the number of characters to manage long text input appropriately in the UI (for example, by displaying a bigger text box).

**Comment by dennishofs** [comment]
Implemented as <<input type="longtext" ...>> in exactly the same format as <<input type="text" ...>>
