### ISSUE TITLE
WOOL Editor - Feature: Warning if a statement contains https://

### ISSUE THREAD

**Issue by dennishofs** [woolplatform/wool#72]
**Please describe what you would like to see added or changed to the WOOL Editor:**

If a statement contains http:// or https://, the part from // is seen as a comment. It needs to be escaped like https:\\//. Since it is very easy to forget about this, it would be nice if the editor gives a warning if it sees http:// or https://.

**Comment by borisvanschooten** [comment]
http(s):\// is now understood as an URL.  Editor now gives a warning when encountering a bare http(s)://.
