### ISSUE TITLE
WOOL Editor - Feature: Preserve file EOL

### ISSUE THREAD

**Issue by borisvanschooten** [woolplatform/wool#88]
EOL is apparently always converted to LF when saving a file. It's better to preserve the CRLF or LF of the original file.

**Comment by borisvanschooten** [comment]
In retrospect, I would like to know a little more about the use cases for this feature.  Is this because the files are sometimes opened in a Windows text editor which converts the LF to CRLF?

**Comment by dennishofs** [comment]
I always find the problem with git that all files seem to have changed because their line endings changed when you edit files in the WOOL editor. I think it's good to follow the current line ending of an opened file, or use the system default for new files, like most text editors do.

**Comment by borisvanschooten** [comment]
Fixed in 1.10.8. EOL type is now shown next to the filename.
