### ISSUE TITLE
WOOL Editor - Bug: Unnecessary warnings for unsaved changes

### ISSUE THREAD

**Issue by dennishofs** [woolplatform/wool#93]
**Editor Version:**
v1.10.2

**Desktop or Web version:** 
Desktop

**Operating System (Desktop) or Browser (Web):**
Windows

**Describe the Issue:**
When you load another dialogue with a double click in the file browser you get the message "Changes may not have been saved, proceed?" This also appears when you didn't change anything. Moreover the message does not appear when you single click.

**Comment by borisvanschooten** [comment]
Double click on a file is not a feature of the file browser. If I click on a file twice in quick succession, I get the "changes not saved" dialog because the old file did not finish processing. Solution would be to prevent load until the file finished processing.

**Comment by borisvanschooten** [comment]
Fixed. The problem occurs only with the initial start.wool, because the initial content is slightly different from what the editor would save.
