### ISSUE TITLE
WOOL Editor - Bug: Error if project directory already exists

### ISSUE THREAD

**Issue by dennishofs** [woolplatform/wool#96]
**Editor Version:**
1.10.2

**Desktop or Web version:** 
Desktop

**Operating System (Desktop) or Browser (Web):**
Windows

**Describe the Issue:**
I created an empty project directory in the explorer before creating a new project in the editor. The editor then says "Cannot initialize project because an error occurred." Ideally it does not give an error at all when the directory is empty. Otherwise the error message could be clearer.

**Comment by dennishofs** [comment]
When I get this error there is a Previous button, but it doesn't do anything when I click it.

**Comment by borisvanschooten** [comment]
I would like the create project function to remain "fail fast". It now shows the reason for the error so the user knows why it failed.
