### ISSUE TITLE
WOOL Editor - Bug: Previous file shown after creating new project

### ISSUE THREAD

**Issue by dennishofs** [woolplatform/wool#97]
**Editor Version:**
1.10.2

**Desktop or Web version:** 
Desktop

**Operating System (Desktop) or Browser (Web):**
Windows

**Describe the Issue:**
I had a project open in the editor and then created a new project. After the project was created, the editor still showed the contents of the old WOOL file.

**Comment by borisvanschooten** [comment]
Fixed in next release.
