### ISSUE TITLE
WOOL Editor - Bug: File selection changes after cancel in save warning

### ISSUE THREAD

**Issue by dennishofs** [woolplatform/wool#98]
**Editor Version:**
1.10.2

**Desktop or Web version:** 
Desktop

**Operating System (Desktop) or Browser (Web):**
Windows

**Describe the Issue:**
If I make a change and then select another file in the file browser, I get the message "Changes may not have been saved, proceed?" If I click Cancel, the selection in the file browser changes nonetheless.

**Comment by borisvanschooten** [comment]
Fixed in 1.10.8.
